### PR TITLE
stage-2 implementation

### PR DESCRIPTION
**Pull request by shimritz**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Great job with your diploma project! Some issues will be necessary to correct, but on the whole it looks pretty good!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Most of the text elements in the project have icorrect font-family, please check the design, there are three families used: Inter, Roboto, Roboto Slab. Note that "Roboto" and "Roboto Slab" are two different font-families, they even have different types: the first one is sans-serif, the second one - serif
* https://skr.sh/sHHOmSjKR65 https://skr.sh/sHHqTgVQ3Fq https://skr.sh/sHHfPSVOtQC Design mismatches. Please, check elements typography values and alignment with the design.
* https://skr.sh/sHHkxODJCCK Layout doesn't correspond to the design
* The active page should be underlined https://skr.sh/sHHzKHsvnZM
* Mobile layout is broken https://skr.sh/sHHTgVlGLSQ
* https://skr.sh/sHHZn7WYT2n

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Tha page scrolls on resolutions 1362px and smaller.
* Tablets and desktops should have three cards in a row: https://skr.sh/sHHNX2EuXNJ. Cards shouldn't be that narrow and long.
* There should be no white margins here: https://skr.sh/sHH1Dd7FZAV
* https://skr.sh/sHHTgVlGLSQ Mobile layout is broken

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* footer should contain working links opening in new tabs
* navigation doesn't work
* preloader and nothing-found are not displayed

- [x]  Classes are named according to BEM specifications.

* Element outside the block https://skr.sh/sHHLkFlzsxp https://skr.sh/sHHaff1jaU7 (also incorrectly used modifier)
* BEM entity can't be formed only with a modifier https://skr.sh/sHHo0eyspPw https://skr.sh/sHHQwPHXBL5

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* There should be only one h1 per page.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.

* https://skr.sh/sHHNBpyAeMb

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* https://skr.sh/sHH4KpIR4US

- [x]  Images have an `alt` attribute containing appropriate values.

* Singout icon

- [x]  Raster and vector images have been optimized.

## Number of points: 42

**Comment by ImaliaNsk** [comment]
Thank you for the corrections, the project looks much better! However, it will require further work, especially with responsive layout.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://skr.sh/sHV8lfqed3y Incorrect font-family
* https://skr.sh/sHV4Q6qL14T Incorrect font-family for search results title, incorrect font-size for the page heading
* https://skr.sh/sHVkg1bEYJx layout mismatch: closing button size and placement, the width of the content in the popup container

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The layout breaks and scrolls horizontally on 321 - 727
* The page content should be centered https://skr.sh/sHV87gmiTXC

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* https://skr.sh/sHVnk8xmwCE There should be a link to Saved-news, and the menu should be possible to close.
* preloader and nothing-found are not displayed

- [x]  Classes are named according to BEM specifications.

* https://skr.sh/sHVhyerlVVE Should be `popup_type_sign-in`, `popup_type_sign-up`
* https://skr.sh/sHVToABa2n4 Incorrectly used modifier, outside its block

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* There should be only one h1 per page.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* https://skr.sh/sHVIujfpOZd please correct all similar cases.

- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 52

**Comment by shimritz** [comment]
hey, the comment about  preloader and the not found components is not relevant for this branch - on stage 2 we dont have to display it(only to prepare them) and only display it on stage-3

**Comment by ImaliaNsk** [comment]
Good job, the project is getting better! However, there are still issues that require fixing.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://skr.sh/sHbkYYh0kjP?a The popup layout doesn't match the design. Please compare: https://skr.sh/sHbYYSVgZmF. Note the background image that's use as an overlay, it should be removed, it doesn't correspond to the design.
* No gaps between elements https://skr.sh/sHb2XCMmLtV
* https://skr.sh/sHbOaECau0i

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Both pages scrolls on 521 - 605

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* `preloader` and `nothing found` can not be displayed. This stage doesn't require search to work properly yet, but it requires all component to be coded, and possible to render on the page. You can add flags or simply remove `display: none` for them and leave them displayed on the page on loading. Make sure they are displayed correctly, exactly as designed in figma.

- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* There should be only one h1 per page. The title in "Nothing found" and the title in the popups can't be h1 level, they are not main headings of the page.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* Please correct all similar cases https://skr.sh/sHbolBjX2l1. You can use search on your IDE to find and fix all such cases.

- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 56

**Comment by ImaliaNsk** [comment]
Amazing progress, thanks for the fixes! The score is enough to move on to the next stage, congratulations! I wish you success on stage 3!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://skr.sh/sHcl1k87RMZ the popup doesn't need a background image for the overlay
* The button is incorrectly aligned https://skr.sh/sHc6okAn5EB
* https://skr.sh/sHcOEX6lEAi preloader is positioned incorrectly.
* Incorrect font-family: https://skr.sh/sHcUTn1C2Nb
* https://skr.sh/sHcdji9mzv5 Big dark-gray empty space should be removed, please compare to the design https://skr.sh/sHcXsO1tZL4

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [ ]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.

* Preloader is positioned incorrectly, circle-preloader element has absolute, but the parent doesn't have relative

- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 83

**Pull request merged**
